apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-minikube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-minikube-app
  template:
    metadata:
      labels:
        app: kubernetes-minikube-app
    spec:
      containers:
        - name: kubernetes-minikube-container
          image: arghunmousanezhad/kubernetes-minikube:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-minikube-service
spec:
  type: NodePort
  selector:
    app: kubernetes-minikube-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
